### ISSUE TITLE
Workflow loop with new published version commit everytime the job completes

### ISSUE THREAD

**Issue by aadi1011** [ServiceNow/sncicd-publish-app#65]
#### Summary

When using the `sncicd-publish-app` GitHub Action as part of a PR-based CI/CD pipeline, the action publishes a new application version **and creates a new commit in the GitHub repository.**

That commit (usually with message: `Published App Version: <version>`) **triggers the workflow again**, leading to an infinite loop.

This causes:
- Repeated execution of the workflow
- Potential app version conflicts (like `Invalid application version downgrade`)
- Unexpected side effects such as build congestion and unnecessary ATF executions

---

### Steps to reproduce

1. Setup a GitHub Actions workflow triggered on `pull_request` or `push`
2. Use the `sncicd-publish-app` action like below:

```yaml
- name: ServiceNow CI/CD Publish App
  id: publish_app
  uses: ServiceNow/sncicd-publish-app@2.0.1
  with:
    versionTemplate: 1.1
    versionFormat: template
  env:
    nowUsername: ${{ secrets.SN_USERNAME }}
    nowPassword: ${{ secrets.SN_PASSWORD }}
    nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
    appSysID: ${{ secrets.SN_APP_SYSID }}
```

#### Screenshot for reference:

![Image](https://github.com/user-attachments/assets/85261cd1-bb63-475e-9ac0-90884a7dc274)

3. The action publishes an app version and **commits back to the repo**
 
4. That commit re-triggers the same workflow, even if filters like `if: "!startsWith(github.event.head_commit.message, 'Published')"` are used.

#### But this commit is:
1. Not marked as a bot or system commit
2. Not suppressible with filters like `head_commit.message` in PR-based workflows

### Proposed Fixes / Enhancements
1. Add a flag to disable commit back to GitHub
Example: `commitChanges: false` — skip the push altogether
2. Mark the commit with a special flag or author
So we can reliably filter based on `github.actor == 'servicenow-bot'` or similar
3. Emit a special output or tag we can use in if: conditions (like is_publish_commit = true)

### Action Version Used
`ServiceNow/sncicd-publish-app@2.0.1`

### Request
Please consider adding a config to disable GitHub commits, or make the commits easily detectable for conditional filtering.

Thanks
